[package]
name = "chaindb-node"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tracing = { workspace =true }
libp2p = {workspace = true}
chaindb-common = { path = "../common" }

[[bin]]
name = "node"
path = "bin/main.rs"
doctest = false
test = false
